### ISSUE TITLE
Controller: Link

### ISSUE THREAD

**Issue by berenteb** [kir-dev/startlap-sch#10]
Things missing from the generated controller:

- ~~implement the CreateLinkDto. It should have all the fields of Link that the user will have to enter in a form.~~ 
- add an optional query parameter to the findAll method, pass it down to the service, which should filter the links based on this search term. For now it's perfectly fine if it just searches in the link title.

**Comment by Tschonti** [comment]
some help for basic filtering with prisma:
https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting
