### ISSUE TITLE
Model: User

### ISSUE THREAD

**Issue by berenteb** [kir-dev/startlap-sch#4]
**The model should contain the following:**

- username - string
- email - string
~- profilePictureUrl - string (in the Moscow matrix, this is a could have)~
- internalId - string (authSch)
- submissions - Submission[] (relation) (align with team/person assigned to that)
- role - enum (or string): USER, EDITOR, ADMIN (MARKETING?)

**Acceptance Criteria:**
- Prisma scheme is created and is usable
- Submissions are connected

**Comment by KostyalBalint** [comment]
POD D gruppen
